### ISSUE TITLE
Gear Ratio for Pololu 37D gearmotors

### ISSUE THREAD

**Issue by pkr97** [michiganrobotics/rob311#2]
Hi, What is the gear ratio and power rating of the motor used to build the robot?

Thanks...

**Comment by halldm3663** [comment]
did anyone ever get back to you on this?

**Comment by michiganrobotics** [comment]
Hello -- apologies for the delay.

The gear ratio of the motor is 70:1 and other motor specification can be found here: https://www.pololu.com/product/4754/resources
