### ISSUE TITLE
U-M Robotics Pico Board: Open Source?

### ISSUE THREAD

**Issue by pkr97** [michiganrobotics/rob311#3]
Hi, in Lab-8 I see that U-M Robotics Pico Board is used to control the wheels and an additional Raspberry Pi for High-level control.
https://github.com/michiganrobotics/rob311/blob/main/Labs/Lab%2008%20-%20Reading%20and%20plotting%20data/ROB%20311%20-%20Lab%208%20-%20Flashing%2C%20reading%2C%20and%20plotting.pdf

I was wondering if the U-M Robotics Pico Board is available outside for buying or if the design is open.

If not, can we just have a connection diagram for Pico and DRV8874?

Thanks...

**Comment by michiganrobotics** [comment]
Hello -- please find the control board specifics here:
https://github.com/mbot-project/mbot_hardware/tree/main/mbot_control_board

**Comment by williamchan** [comment]
This looks like the order form for the Mbot control board https://available-inventions.umich.edu/product/mbot-control-board
